<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Jellyfin.Plugin.Paywall</RootNamespace>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.11" />
    <PackageReference Include="Jellyfin.Database.Implementations" Version="10.11.11" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Paywall.Infrastructure/Paywall.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Configuration/configPage.html" />
    <EmbeddedResource Include="Configuration/configPage.html" />
  </ItemGroup>
</Project>
